name: CI/CD Tienda Perritos - DB

on:
  push:
    branches: [ "main", "deploy" ]
    paths:
      - ".github/workflows/**"
      - "db/**"
  workflow_dispatch:

jobs:
  build-push-deploy-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR (runner)
      uses: aws-actions/amazon-ecr-login@v1

    - name: Generar y empujar imagen MySQL a ECR
      run: |
        echo "Descargando imagen oficial de mysql temporalmente al runner..."
        docker pull mysql:8.0
        echo "Etiquetándola para nuestro ECR privado..."
        docker tag mysql:8.0 ${{ secrets.ECR_REPO_URL_DB }}:latest
        echo "Subiendo imagen al ECR para que la DB privada pueda descargarla..."
        docker push ${{ secrets.ECR_REPO_URL_DB }}:latest

    - name: Desplegar DB vía SSM (pull desde ECR)
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_DB_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Actualizar tienda-db desde ECR" \
          --parameters '{"commands":[
            "set -e",
            "aws ecr get-login-password --region '\''${{ secrets.AWS_REGION }}'\'' | sudo docker login --username AWS --password-stdin $(echo ${{ secrets.ECR_REPO_URL_DB }} | cut -d/ -f1)",
            "sudo docker pull ${{ secrets.ECR_REPO_URL_DB }}:latest",
            "sudo docker stop tienda-db || true",
            "sudo docker rm tienda-db || true",
            "sudo docker run -d --name tienda-db -p 3306:3306 -e MYSQL_DATABASE=${{ secrets.DB_NAME }} -e MYSQL_ROOT_PASSWORD=${{ secrets.DB_PASSWORD }} -v dbdata:/var/lib/mysql ${{ secrets.ECR_REPO_URL_DB }}:latest"
          ]}' \
          --output text
